### ISSUE TITLE
pip3 missing?

### ISSUE THREAD

**Issue by sgjava** [markus-perl/ffmpeg-build-script#110]
building dav1d - version 0.9.2
=======================
$ python3 -m pip install meson ninja --quiet --no-cache-dir --disable-pip-version-check
/usr/bin/python3: No module named pip

Failed to Execute python3 -m pip install meson ninja --quiet --no-cache-dir --disable-pip-version-check

I just installed pip and reran script.

**Comment by rokibhasansagar** [comment]
#110 and #111 will be fixed after merging #109

**Comment by sgjava** [comment]
Sounds good, got the x265 lib missing, but it looks like that was already addressed by https://github.com/markus-perl/ffmpeg-build-script/issues/73

I should know in a bit.

**Comment by rokibhasansagar** [comment]
> Sounds good, got the x265 lib missing, but it looks like that was already addressed by #73
> 

The issue of pkg-config missing for x265 in various systems still exists, and it also fixes itself by a few random processes.
It's still a common issue found in both sources from Multicoreware and Videolan.
That part was mentioned here too - https://github.com/markus-perl/ffmpeg-build-script/pull/102#issuecomment-917793492

**Comment by sgjava** [comment]
`sudo apt install libnuma-dev` worked on Ubuntu 20.04.

**Comment by markus-perl** [comment]
Closing as stale — this was reported in 2021 against a much older script version, and the meson/ninja bootstrap has been rewritten since (it now warns and falls back to a system meson instead of assuming pip works).

That said, the general area is not fully fixed: on PEP 668 distributions (Ubuntu 24.04+, Debian 12+) the bootstrap still aborts with `externally-managed-environment` when meson is not already installed. That is tracked in #237 — please follow that one if it matches what you hit. Workaround in the meantime: install meson and ninja from your system package manager (`apt install meson ninja-build`) before running the script.
